# Generated by Django 4.0.6 on 2022-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePrice',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.RemoveField(
            model_name='sales_volume',
            name='createitemmod_ptr',
        ),
        migrations.DeleteModel(
            name='CreateItemMod',
        ),
        migrations.DeleteModel(
            name='Sales_Volume',
        ),
    ]
