# Generated by Django 4.0.6 on 2022-07-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manual', '0002_delete_createprice_delete_indicator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateItemMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Продукт', 'Продукт'), ('Услуга', 'Услуга')], default='', max_length=25, verbose_name='Тип')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('unit', models.CharField(choices=[('Услуга', '-'), ('Кг', 'КГ'), ('Гр', 'Г'), ('Шт', 'ШТ'), ('Л', 'Л'), ('Упаковка', 'УПАК')], default='', max_length=40, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': ('Добавить товар/услугу',),
                'verbose_name_plural': 'Добавить товары/услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Цена')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Продукт', 'Продукт'), ('Продукт', 'Услуга')], default='', max_length=25, verbose_name='Тип')),
                ('period_type', models.CharField(choices=[('День', 'День'), ('Месяц', 'Месяц'), ('Квартал', 'Квартал'), ('Год', 'Год')], default='День', max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('price_non_nds', models.IntegerField(default=0, verbose_name='Цена без NDS')),
                ('NDS_type', models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20')], default='0')),
                ('NDS', models.IntegerField(default=0, verbose_name='НДС')),
                ('price_with_nds', models.IntegerField(default=0, verbose_name='Цена с НДС')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование')),
                ('date', models.DateTimeField()),
                ('formula', models.TextField(verbose_name='Формула')),
                ('is_constant', models.BooleanField(default=False, verbose_name='Константа')),
                ('period_start', models.DateField(verbose_name='Начальная дата')),
                ('period_end', models.DateField(verbose_name='Конечная дата')),
                ('calculated_value', models.FloatField(verbose_name='Вычисляемое значение')),
                ('expected_value', models.FloatField(verbose_name='Ожидаемое значение')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sales_Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('day', 'День'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], default='День', max_length=10, verbose_name='Тип временного периода')),
                ('period_start', models.DateField(verbose_name='Начало временного периода')),
                ('period_end', models.DateField(verbose_name='Конец временного периода')),
                ('value_nat', models.FloatField(default='', max_length=10, verbose_name='Значение')),
                ('typeSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeSales', to='manual.createitemmod')),
                ('unitSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitSales', to='manual.createitemmod')),
            ],
            options={
                'verbose_name': 'Создать объём продаж',
                'verbose_name_plural': 'Создать объемы продаж',
            },
        ),
    ]
