# Generated by Django 4.0.6 on 2022-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_delete_createprice_alter_sales_volume_typesale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Продукт', 'Продукт'), ('Продукт', 'Услуга')], default='', max_length=25, verbose_name='Тип')),
                ('date', models.DateField()),
                ('period_type', models.CharField(choices=[('День', 'День'), ('Месяц', 'Месяц'), ('Квартал', 'Квартал'), ('Год', 'Год')], default='День', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('price_non_nds', models.IntegerField(default=0, verbose_name='Цена без NDS')),
                ('NDS_type', models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20')], default='0')),
                ('NDS', models.FloatField(default=0, verbose_name='НДС')),
                ('price_with_nds', models.FloatField(default=0, verbose_name='Цена с НДС')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
