# Generated by Django 4.0.6 on 2022-07-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0005_createprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createprice',
            options={'ordering': ['-date'], 'verbose_name': 'Создать цену', 'verbose_name_plural': 'Создать цены'},
        ),
        migrations.AddField(
            model_name='createitemmod',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createprice',
            name='type',
            field=models.CharField(choices=[('Продукт', 'Продукт'), ('Услуга', 'Услуга')], default='', max_length=25, verbose_name='Тип'),
        ),
    ]
