# Generated by Django 4.0.6 on 2022-07-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePrice',
        ),
        migrations.RemoveField(
            model_name='createsale',
            name='typeSale',
        ),
        migrations.RemoveField(
            model_name='createsale',
            name='unitSale',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='CreateProduct',
        ),
        migrations.DeleteModel(
            name='CreateSale',
        ),
    ]
