# Generated by Django 4.0.6 on 2022-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprice',
            name='typePrice',
        ),
        migrations.RemoveField(
            model_name='createproduct',
            name='typeProduct',
        ),
        migrations.RemoveField(
            model_name='createproduct',
            name='unitProduct',
        ),
        migrations.RemoveField(
            model_name='createsale',
            name='typeSale',
        ),
        migrations.RemoveField(
            model_name='createsale',
            name='unitSale',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='CreatePrice',
        ),
        migrations.DeleteModel(
            name='CreateProduct',
        ),
        migrations.DeleteModel(
            name='CreateSale',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
