# Generated by Django 4.0.6 on 2022-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameManual', models.CharField(max_length=70, verbose_name='Наименование')),
                ('typeManual', models.CharField(choices=[('common', 'Простой'), ('time series', 'Временной ряд')], default='', max_length=70, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Создать справочник',
                'verbose_name_plural': 'Создать справочники',
            },
        ),
    ]
